### ISSUE TITLE
Hungint Area Epic (tracking each area I have left)

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#763]
Look into suggestions for these areas

### BADLANDS 
- 2830 ,2958
- [x] REMOVE ALL THE LOW END MOBS SUCH AS SKELETION WARRIORS/ BEHOLDERS/ AND ALL LOW CLASS MOBS
- [x] ADD FLOATING HORROR TO NORTH PART OF BAND LANDS
- [x] ADD NIGHTMARE/MINIONS TO EAST SIDE
- [x] ADD DRETCH/ABISHI TO WEST SIDE 
- [x] ADD LICHES AND ILLITHID MAGES TO MIDDLE
- [x] ADD A SMALL DEMON/HELL SPAWN SPAWN TO SOUTH SIDE.

### LOTORS CASTLE ETTINS / SG
- [x] ADD MORE ETTINS/STORM GIANTS/STONE GIANTS

**Comment by PatrickKaHoTang** [comment]
**Hell - additional ideas, subject to change**
- Around both portals entering hell starts with the lower level hell monsters then gets gradually harder the deeper they go after certain chokepoints (labeled with 2 vertical lines - can be changed)
- Monsters in hell will need some level altering 
_*Note: up for debate on Hell being a level 40 starting area due to Nightmares already outside by Parian, Garnea, Lyrina and right of Desprial_ 
- Give Rune drops back to hell monsters above level 60 exclusively (Minions, Horned Devils, Demons, Hell Spawns, Balrons)
- Unpopular opinion: Portal to Skull Island moved into Talazar's Castle? (Remove all gates and open up areas around castle so it's not a choke point)

**Exclusive drop ideas**
- Minions and Horned Devils - Rune Gauntlets (much lower chance than Demons)
- Demons - Rune Gauntlets, Rune Shield (much lower chance than Hell Spawns)
- Hell Spawns - Rune Leggings, Rune Shield
- Balrons - Rune Helmet, Rune Armour, Rune Sword

![Hell](https://github.com/IronWillGames/Dransik/assets/30209039/a4441f36-1166-44da-b694-7a2e6224eb92)

**Comment by PatrickKaHoTang** [comment]
**New Winterland Area by Osgarl**

- Create a level new 50-80 area with new or non-utilized cold/normal monsters
- Underground area? Nothing extremely big. Smaller than Anubis size but as open as underground Toxicum
- Should have multiple entrances/exits (red x's can be moved)
- Possibly a new set of gear or specialized items?
- Could utilize one of the weaker bosses (Muspimerol and/or Haltija) or use other sprites not utilized in the game already
_*Note: Will need to remove their respawns at other bosses if Muspimerol and/or Haltija_

![New WL Area](https://github.com/IronWillGames/Dransik/assets/30209039/eba57b18-2080-4866-b659-a2f11fddc3ef)

**Comment by davidjreese** [comment]
Thanks for the suggestions here. I will see what I can do.

**Comment by davidjreese** [comment]
Not going to change this one - I think its pretty good after giving storm giants lightning attacks just noting it here

### STORM GIANT LAIR / VALLEY OF GIANTS

- [ ] ADD MORE STORM GIANTS / GOLEMS ALL THROUGHOUT 
- [ ] ADD STONE GIANTS
- [ ] ADD ROCK TROLLS

**Comment by davidjreese** [comment]
All is done from this original ticket and some items were 'new areas' so I moved the information to another ticket
