### ISSUE TITLE
Implement: New Rings, Necklaces, Belts

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#886]
**Part 1**

New ticket in combination of: 
- https://github.com/IronWillGames/Dransik/issues/881
- https://github.com/IronWillGames/Dransik/issues/882
- https://github.com/IronWillGames/Dransik/issues/883

Added stats to the following items

Rings

All setup in shops and TCs just need to finish setting up on NPCS or quests where appropriate

- [x] Ring of Lesser Strength (TC3)
- [x] Ring of Lesser Dexterity (TC3)
- [x] Ring of Lesser Intelligence (TC3)
- [x] Ring of Lesser Constitution (TC3)
- [x] Ring of Strength (TC4)
- [x] Ring of Dexterity (TC4)
- [x] Ring of Intelligence (TC4)
- [x] Ring of Constitution (TC4)
- [x] Ring of Greater Strength (TC5)
- [x] Ring of Greater Dexterity (TC5)
- [x] Ring of Greater Intelligence (TC5)
- [x] Ring of Greater Constitution (TC5)
- [ ] Band of Silvest (Any of Silvest Librarian quest rewards) -> NEED TO ADD TO QUEST REWARD (Add Jewler to Silvest?)
- [ ] Rusted Arcana Signet (Quest reward for mages on Silvest or TC2) -> NEED TO ADD TO A QUEST IN Silvest
- [ ] Alektorous Ring (where to drop?)
- [ ] Ring of Ixion (where to drop?)
- [ ] Canidaeus Ring (where to drop?)

Amulets

All setup in shops and TCs just need to finish setting up on NPCS or quests where appropriate

- [x] Amulet of Lesser Strength (TC3)
- [x] Amulet of Lesser Dexterity (TC3)
- [x] Amulet of Lesser Intelligence (TC3)
- [x] Amulet of Lesser Constitution (TC3)
- [x] Amulet of Strength (TC4)
- [x] Amulet of Dexterity (TC4)
- [x] Amulet of Intelligence (TC4)
- [x] Amulet of Constitution (TC4)
- [x] Amulet of Greater Strength (TC5)
- [x] Amulet of Greater Dexterity (TC5)
- [x] Amulet of Greater Intelligence (TC5)
- [x] Amulet of Greater Constitution (TC5)
- [ ] Necklace of Silvest (Any of Silvest Librarian quest rewards) -> NEED TO ADD TO QUEST REWARD (Add Jewler to Silvest?)

Belts

All setup in shops and TCs just need to finish setting up on NPCS or quests where appropriate

- [x] Belt of Lesser Strength (TC3)
- [x] Belt of Lesser Dexterity (TC3)
- [x] Belt of Lesser Intelligence (TC3)
- [x] Belt of Lesser Constitution (TC3)
- [x] Belt of Strength (TC4)
- [x] Belt of Dexterity (TC4)
- [x] Belt of Intelligence (TC4)
- [x] Belt of Constitution (TC4)
- [x] Belt of Greater Strength (TC5)
- [x] Belt of Greater Dexterity (TC5)
- [x] Belt of Greater Intelligence (TC5)
- [x] Belt of Greater Constitution (TC5)
- [ ] Sash of Silvest (Any of Silvest Librarian quest rewards) -> NEED TO ADD TO QUEST REWARD (Add Jewler to Silvest?)
- [ ] Girdle of the Fallen (Stone Giant, Undead Altar Boy, and/or Ogre - your choice)
- [ ] Waistband of Cold Protection (Yeti, Frost Troll, Frost Giant)
- [ ] Waistband of Fire Protection (Phoenix, Nightmare)
- [ ] Waistband of Electric Protection (Shriek, Troll - also need more electric type monsters)
- [ ] Waistband of Acid Protection (Dretch, Floating Horror)
- [ ] Waistband of Poison Protection (Funguilia, Grimlock, Fungi Lurker)
- [ ] Waistband of Disease Protection (Oglahs, Oglah Soldiers, Greater Oglahs)

**Comment by PatrickKaHoTang** [comment]
**Part 2**

Rings

All setup in shops or TCs  (just need to finish placing them on NPCS, Quests as appropriate)

- [x] Band of Shallow Whispers (TC3)
- [ ] Loop of Limitless Thought (One of the bosses in new dungeon)
- [ ] Hoop of Peerless Power (Void Patriarch, Weeping Winter, Fulgur, Nycadaemon, Shalox)
- [ ] Ring of Unbroken Velocity (Void Patriarch, Weeping Winter, Fulgur, Nycadaemon, Shalox)
- [ ] Band of Enduring Vigor (Void Patriarch, Weeping Winter, Fulgur, Nycadaemon, Shalox)
- [ ] Loop of Clairvoyance (Void Patriarch, Weeping Winter, Fulgur, Nycadaemon, Shalox)
- [ ] Hoop of Nimble Precision (One of the bosses in new dungeon)
- [ ] Ring of the Immovable (One of the monsters in new dungeon)
- [ ] Barbarian's Ring of Dominance (One of the bosses in new dungeon)
- [ ] Ring of Eight (Venom Spider, Anarius, Renegade Leader, King Styx, Stone Golem - your choice, low %)
- [ ] Rusted Iron Ring (Fishing if possible, otherwise TC1)
- [ ] Corroded Copper Ring (Fishing if possible, otherwise TC1)
- [x] Silver Ring (TC1)
- [x] Gold Ring (TC2)
- [ ] Signet of Ice (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)
- [ ] Signet of Flame (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)
- [ ] Signet of Thunder (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)
- [ ] Caustic Signet (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)
- [ ] Signet of Toxins (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)
- [ ] Signet of Blight (Centaur, Centaur Warrior, Storm Giant, Golem, Renegade and others - maybe 0.07% or something like that?)

Belts

All setup in shops and TCs just need to finish setting up on NPCS or quests where appropriate

- [ ] Defender's Belt (Void Zealot, Balrons, Stygian Essence, Anubis, Orcus)
- [ ] Warrior's Mighty Girdle (Void Zealot, Balrons, Stygian Essence, Anubis, Orcus)
- [ ] Ranger's Evasive Sash (Void Zealot, Balrons, Stygian Essence, Anubis, Orcus)
- [ ] Scholar's Wisdom Sash (Void Zealot, Balrons, Stygian Essence, Anubis, Orcus)
- [ ] Champion's Belt (Anarius, Floating Monstrosity, Elder Elemental Dragons)
- [ ] Girdle of Unwavering Bulwark (One of the monsters in new dungeon)
- [ ] Sash of Unrivaled Intellect (One of the bosses in new dungeon)
- [ ] Strap of Boundless Brawn (One of the bosses in new dungeon)
- [ ] Belt of Remarkable Reflex (One of the bosses in new dungeon)
- [x] Twisted Rope Sash (TC2)
- [x] Wide Buckle (TC3)
- [ ] Durable Buckle (Ettin, Storm Giant, Golem)
- [ ] Reinforced Girdle (Storm Giant, Golem - slightly lower % than Durable Buckle)

**Comment by PatrickKaHoTang** [comment]
**Part 3**

Rings

- [ ] Ring of Lesser Resistance
- [ ] Ring of Resistance
- [ ] Dark Ring of the Archer (New Frigits or Nelms)
- [ ] Dark Ring of the Ettin (New Frigits or Nelms)
- [ ] Dark Ring of the Golem (New Frigits or Nelms)
- [ ] Dark Ring of the Magi (New Frigits or Nelms)
- [ ] Dark Ring of the Ogre (New Frigits or Nelms)
- [ ] Dark Ring of the Wraith (New Frigits or Nelms)
- [x] Dragon's Eye (Regular Dragons)
- [x] Elder Dragon's Eye (Elder Dragons)
- [ ] Ring of Health

Belts

- [x] Dragon Scale Belt (Elder Dragons, low % and regular Dragons, even lower %)

**Comment by PatrickKaHoTang** [comment]
Part 4

Necklace

- [x] Locket of Ancient Memories

**Comment by davidjreese** [comment]
Locket is in another ticket, with some items that need code/script support. Unchecked items still nee to be done.

This is the cutoff for the Travaal/WWL/Mage release
